display_name: Geek Chat
msix_version: 0.0.1.1
publisher_display_name: Geek Chat
identity_name: com.macgeeker.geekchat
capabilities: internetClient, location
install_certificate: 'false'
logo_path: assets/icon.png